pub usingnamespace @import("GenericVector.zig");
pub usingnamespace @import("Mat3.zig");
pub usingnamespace @import("Mat4.zig");
pub usingnamespace @import("Quaternion.zig");
pub usingnamespace @import("util.zig");
const math = @import("std").math;
pub usingnamespace math;
pub const one_over_pi = 1.0 / math.pi;
pub const pi_over_two = math.pi / 2.0;
pub const pi_over_three = math.pi / 3.0;
pub const pi_over_four = math.pi / 4.0;
pub const pi_over_six = math.pi / 6.0;
pub const radians_per_degree = math.pi / 180.0;
pub const degrees_per_radian = 180.0 / math.pi;
pub const tow_pi = math.tau;
